---
- name: Update all packages
  ansible.builtin.dnf:
    name: 
      - "*"
      - kernel
    state: latest

- name: Check if reboot is required
  ansible.builtin.command: needs-restarting -r
  register: reboot_required
  ignore_errors: yes

- name: display result
  debug:
    var: reboot_required.rc

- name: Reboot the server
  ansible.builtin.reboot:
    post_reboot_delay: 30
  when: reboot_required.rc == 1