---
- name: Simple Container Remediation
  hosts: baremetal
  become: true

  tasks:
    - name: Restart the Nginx docker container
      containers.podman.podman_container:
        name: webapp
        state: started
        restart: true

    - name: Check that you can connect (GET) to a page and it returns a status 200
      ansible.builtin.uri:
        url: https://splash.bluehatlab.net
