---
- name: Advanced Container Remediation
  hosts: baremetal
  become: true

  tasks:
    - name: Stop the existing container
      containers.podman.podman_container:
        name: webapp
        state: stopped

    - name: Remove the existing container
      containers.podman.podman_container:
        name: webapp
        state: absent

    - name: Create the container again
      containers.podman.podman_container:
        name: webapp
        image: docker.io/library/nginx:latest
        state: present
        ports:
          - "0.0.0.0:80:80/tcp"

    - name: Start the container
      containers.podman.podman_container:
        name: webapp
        state: started

    - name: Check that you can connect (GET) to a page and it returns a status 200
      ansible.builtin.uri:
        url: https://splash.bluehatlab.net
