---
- name: Cordon node
  ansible.builtin.command: >-
    /usr/local/bin/kubectl cordon
    {{ kube_override_hostname|default(inventory_hostname) }}
  delegate_to: "{{ groups['kube_control_plane'][0] }}"

- name: Wait for node to cordon
  ansible.builtin.command: >-
    /usr/local/bin/kubectl get node
    {{ kube_override_hostname|default(inventory_hostname) }}
    -o json
  register: wait_for_cordon
  retries: 10
  delay: 10
  delegate_to: "{{ groups['kube_control_plane'][0] }}"
  changed_when: false
  until: (wait_for_cordon['stdout'] | from_json).spec.unschedulable

- name: Drain node
  ansible.builtin.command: >-
    /usr/local/bin/kubectl drain
    --force
    --ignore-daemonsets
    --grace-period 300
    --timeout 360s
    --delete-local-data {{ kube_override_hostname|default(inventory_hostname) }}
  delegate_to: "{{ groups['kube_control_plane'][0] }}"
