---
- name: Simple Container Remediation
  hosts: baremetal
  become: true

  tasks:
    - name: Recreate container without ports
      containers.podman.podman_container:
        name: webapp
        state: started
        recreate: true
        ports:
          - "9002"
