---
- name: Uncordon node
  ansible.builtin.command: >-
    /usr/local/bin/kubectl uncordon
    {{ kube_override_hostname|default(inventory_hostname) }}
  delegate_to: "{{ groups['kube_control_plane'][0] }}"

- name: Wait for node to uncordon
  ansible.builtin.command: >-
    /usr/local/bin/kubectl get node
    {{ kube_override_hostname|default(inventory_hostname) }}
    -o json
  register: wait_for_uncordon
  retries: 10
  delay: 10
  delegate_to: "{{ groups['kube_control_plane'][0] }}"
  changed_when: false
  until: not (kubectl_get_node['stdout'] | from_json).spec.unschedulable is defined
